Controllers/API/WishlistController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NextCommerce.Data;
using NextCommerce.Data.Entities;

namespace NextCommerce.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class WishlistController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<WishlistController> _logger;

        public WishlistController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, ILogger<WishlistController> logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }

        [HttpPost]
        [Route("add-to-wishlist")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<ActionResult> Add(int id, CancellationToken cancellationToken)
        {
            var user = await _userManager.GetUserAsync(User);

            var product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id, cancellationToken);

            if (product == null) return BadRequest("El producto no existe o no está disponible.");

            var isAlreadyInWishlist = await _context.Wishlist
                .AnyAsync(i => i.User == user && i.Product == product, cancellationToken);

            if (!isAlreadyInWishlist)
            {
                await _context.Wishlist.AddAsync(new WishItem
                {
                    Product = product,
                    User = user,
                    CreatedAt = DateTimeOffset.Now
                }, cancellationToken);

                await _context.SaveChangesAsync(cancellationToken);
            }

            return Ok();
        }

        [HttpPost]
        [Route("remove-from-wishlist")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<ActionResult> Delete(int id, CancellationToken cancellationToken)
        {
            var user = await _userManager.GetUserAsync(User);

            var product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id, cancellationToken);

            var wishItem = await _context.Wishlist.FirstOrDefaultAsync(i => i.User == user && i.Product == product, cancellationToken);

            if (wishItem == null) return BadRequest("Este producto no existe o ya ha sido eliminado de tu lista de deseos anteriormente.");

            _context.Wishlist.Remove(wishItem);
            await _context.SaveChangesAsync(cancellationToken);

            return Ok();
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using NextCommerce.Data;
using NextCommerce.Data.Entities;
using NextCommerce.Extensions;
using NextCommerce.Models.API;
using NextCommerce.Services.Interfaces;

namespace NextCommerce.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly ILogger<CartController> _logger;

        public CartController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IShoppingCartService shoppingCartService, ILogger<CartController> logger)
        {
            _context = context;
            _userManager = userManager;
            _shoppingCartService = shoppingCartService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var cart = new CartViewModel();

            if (User.IsAuthenticated())
            {
                var user = await _userManager.GetUserAsync(User);
                cart = await _shoppingCartService.GetCartFromUser(user.Id);
            }
            else
            {
                var shoppingSessionId = HttpContext.Session.GetShoppingSessionId();

                if (shoppingSessionId.HasValue)
                    cart = await _shoppingCartService.GetCartFromSession(shoppingSessionId.Value);
            }

            return View(cart);
        }

        public async Task<IActionResult> Remove(int id)
        {
            ShoppingSession? shoppingSession = null;

            var shoppingSessionQuery = _context.ShoppingSessions
                .Include(s => s.User)
                .Include(s => s.CartItems);

            if (User.IsAuthenticated())
            {
                var user = await _userManager.GetUserAsync(User);
                shoppingSession = await shoppingSessionQuery.FirstOrDefaultAsync(s => s.UserId == user.Id);
            } else
            {
                var shoppingSessionId = HttpContext.Session.GetShoppingSessionId();
                shoppingSession = await shoppingSessionQuery.FirstOrDefaultAsync(s => s.Id == shoppingSessionId && !s.UserId.HasValue);
            }

            var cartItem = shoppingSession?.CartItems.FirstOrDefault(i => i.Id == id);

            if (shoppingSession == null || cartItem == null) return NotFound();

            shoppingSession.CartItems.Remove(cartItem);

            await _context.SaveChangesAsync();

            shoppingSession.Total = shoppingSession.CartItems.Sum(c => c.UnitPrice * c.Quantity);
            shoppingSession.Taxes = shoppingSession.CartItems.Sum(c => c.UnitTaxes * c.Quantity);

            await _context.SaveChangesAsync();

            return RedirectToActionPermanent(nameof(Index));
        }

        public async Task<IActionResult> RemoveAll()
        {
            ShoppingSession? shoppingSession = null;

            var shoppingSessionQuery = _context.ShoppingSessions
                .Include(s => s.User)
                .Include(s => s.CartItems);

            if (User.IsAuthenticated())
            {
                var user = await _userManager.GetUserAsync(User);
                shoppingSession = await shoppingSessionQuery.FirstOrDefaultAsync(s => s.UserId == user.Id);
            }
            else
            {
                var shoppingSessionId = HttpContext.Session.GetShoppingSessionId();
                shoppingSession = await shoppingSessionQuery.FirstOrDefaultAsync(s => s.Id == shoppingSessionId && !s.UserId.HasValue);
            }

            if (shoppingSession == null) return NotFound();

            shoppingSession.CartItems.Clear();
            shoppingSession.Total = 0;
            shoppingSession.Taxes = 0;

            await _context.SaveChangesAsync();

            return RedirectToActionPermanent(nameof(Index));
        }
    }
}

Controllers/CheckoutController.cs
using FluentEmail.Core.Models;
using Hangfire;
using HashidsNet;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NextCommerce.Data.Entities;
using NextCommerce.Extensions;
using NextCommerce.Models;
using NextCommerce.Services.Interfaces;

namespace NextCommerce.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingSessionService _shoppingSessionService;
        private readonly IStripePaymentIntentService _stripePaymentIntentService;
        private readonly IOrderService _orderService;
        private readonly Hashids _hashIds;
        private readonly IEmailService _emailService;
        private readonly IEmailViewModelService _emailViewModelService;
        private readonly IBackgroundJobClient _backgroundJob;
        private readonly ILogger<CheckoutController> _logger;

        public CheckoutController(IShoppingSessionService shoppingSessionService, IStripePaymentIntentService stripePaymentIntentService, IOrderService orderService, Hashids hashIds, IEmailService emailService, IEmailViewModelService emailViewModelService, IBackgroundJobClient backgroundJob, ILogger<CheckoutController> logger)
        {
            _shoppingSessionService = shoppingSessionService;
            _stripePaymentIntentService = stripePaymentIntentService;
            _orderService = orderService;
            _hashIds = hashIds;
            _emailService = emailService;
            _emailViewModelService = emailViewModelService;
            _backgroundJob = backgroundJob;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var shoppingSession = await _shoppingSessionService.GetFromHttpContext(HttpContext);

                if (!string.IsNullOrEmpty(shoppingSession.CurrentStripePaymentIntentId))
                    await _stripePaymentIntentService.Cancel(shoppingSession.CurrentStripePaymentIntentId);

                var paymentIntent = await _stripePaymentIntentService.CreateFromHttpContextShoppingSession(HttpContext);

                await _shoppingSessionService.UpdateStripePaymentIntentId(shoppingSession.Id, paymentIntent.Id);

                return View(new CheckoutViewModel(shoppingSession, paymentIntent.ClientSecret));
            } catch (Exception ex)
            {
                _logger.LogError(ex, "Error while attempting to load checkout page");

                return RedirectToActionPermanent("Index", "Home");
            }
        }

        public async Task<IActionResult> ProcessSuccessPayment(string payment_intent)
        {
            var paymentIntent = await _stripePaymentIntentService.Get(payment_intent);
            var shoppingSession = await _shoppingSessionService.GetFromHttpContext(HttpContext);

            var order = await _orderService.Create(paymentIntent, shoppingSession.Id);

            await _shoppingSessionService.DeleteFromHttpContext(HttpContext);

            var encodedOrderId = _hashIds.Encode(order.Id);

            var customerAddress = new Address(order.Details.User != null ? order.Details.User.Email : order.Details.Email);

            if (order.Details.Status == Data.Enums.OrderStatus.Pending)
                _backgroundJob.Enqueue(() => _emailService.SendOrderReceived(_emailViewModelService.GetOrderReceivedViewModel(order.Id), new[] { customerAddress }));
            else
                _backgroundJob.Enqueue(() => _emailService.SendOrderReceivedAndPaid(_emailViewModelService.GetOrderReceivedAndPaidViewModel(order.Id), new[] { customerAddress }));

            return RedirectToAction("OrderSuccess", new { hash = encodedOrderId });
        }

        public async Task<IActionResult> OrderSuccess(string hash)
        {
            if (!_hashIds.TryDecodeSingle(hash, out _)) return NotFound();

            var orderId = _hashIds.DecodeSingle(hash);

            var order = await _orderService.Get(orderId);

            if (order.Details.StripePaymentIntentStatus == "requires_action")
            {
                var paymentIntent = await _stripePaymentIntentService.Get(order.Details.StripePaymentIntentId);

                ViewBag.NextAction = paymentIntent.NextAction;
            }

            return View(order);
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NextCommerce.Data;

namespace NextCommerce.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(ApplicationDbContext context, ILogger<ProductsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Detail(string productName)
        {
            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Brand)
                .Include(p => p.Images).ThenInclude(i => i.Image)
                .Include(p => p.Dimension)
                .Include(p => p.Specifications)
                .FirstOrDefaultAsync(p => p.Name == productName);

            if (product == null)
                return NotFound();

            return View(product);
        }
    }
}

Views/Shared/_CookieSection.cshtml
<!-- Coockie Section Start -->
<div class="cookie-bar-section cookiebar-left-section">
    <img src="~/front/images/cookie.png" alt="">
    <div class="content">
        <h3>Aviso de Cookies</h3>
        <p class="font-light">Utilizamos cookies para mejorar su experiencia en nuestro sitio web. Al continuar navegando, acepta nuestro uso de cookies.</p>
        <div class="cookie-buttons">
            <button class="btn btn-solid-default agree-cookies" id="button">Aceptar</button>
            <a href="javascript:void(0)" class="btn default-light1">Rechazar</a>
        </div>
    </div>
</div>
<!-- Coockie Section End -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <link rel="manifest" href="~/front/manifest.json">
    <link rel="icon" href="~/front/images/favicon/4.png" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/front/images/favicon/4.png">
    <meta name="theme-color" content="@(await settings.GetAsync(SettingType.THEME_PRIMARY_COLOR))">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="@(await settings.GetAsync(SettingType.SHOP_STORE))">
    <meta name="msapplication-TileImage" content="~/front/images/favicon/4.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@(await settings.GetAsync(SettingType.SHOP_STORE))">
    <meta name="keywords" content="@(await settings.GetAsync(SettingType.SHOP_STORE))">
    <meta name="author" content="@(await settings.GetAsync(SettingType.SHOP_STORE))">
    @await RenderSectionAsync("SEO", required: false)
    <link rel="icon" href="~/front/images/favicon/1.png" type="image/x-icon" />
    <title>@ViewData["Title"] - @(await settings.GetAsync(SettingType.SHOP_STORE))</title>

    <!-- google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- bootstrap css -->
    <link id="rtl-link" rel="stylesheet" type="text/css" href="~/front/css/vendors/bootstrap.css">

    <!-- font-awesome css -->
    <link rel="stylesheet" type="text/css" href="~/front/css/vendors/font-awesome.css">

    <!-- feather icon css -->
    <link rel="stylesheet" type="text/css" href="~/front/css/vendors/feather-icon.css">

    <!-- animation css -->
    <link rel="stylesheet" type="text/css" href="~/front/css/vendors/animate.css">

    <!-- slick css -->
    <link rel="stylesheet" type="text/css" href="~/front/css/vendors/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="~/front/css/vendors/slick/slick-theme.css">

    <!-- Theme css -->
    <link id="color-link" rel="stylesheet" type="text/css" href="~/front/css/demo1.css">
</head>
<body class="theme-color1 light ltr">
    @await Html.PartialAsync("_Header")
    @await Html.PartialAsync("_MobileMenu")

    @RenderBody()

    @await Html.PartialAsync("_Footer")

    @await Html.PartialAsync("_Modals")

    @if (Context.Request.Cookies["CookieConsent"] == null)
    {
        @await Html.PartialAsync("_CookieSection")
    }

    @await Html.PartialAsync("_ThemeSetting")
    @await Html.PartialAsync("_TapToTopSection")

    <div class="bg-overlay"></div>

    @await Html.PartialAsync("_URLVariables")

    <script>
        document.body.style.setProperty("--theme-color", "@(await settings.GetAsync(SettingType.THEME_PRIMARY_COLOR))");
    </script>

    <!-- latest jquery-->
    <script src="~/front/js/jquery-3.5.1.min.js"></script>

    <!-- Bootstrap js-->
    <script src="~/front/js/bootstrap/bootstrap.bundle.min.js"></script>

    <!-- feather icon js-->
    <script src="~/front/js/feather/feather.min.js"></script>

    <!-- lazyload js-->
    <script src="~/front/js/lazysizes.min.js"></script>

    <!-- Slick js-->
    <script src="~/front/js/slick/slick.js"></script>
    <script src="~/front/js/slick/slick-animation.min.js"></script>
    <script src="~/front/js/slick/custom_slick.js"></script>

    <!-- Timer js -->
    <!--<script src="~/front/js/timer1.js"></script>-->
    <!-- newsletter js -->
    <script src="~/front/js/newsletter.js"></script>

    <!-- Notify js-->
    <script src="~/front/js/bootstrap/bootstrap-notify.min.js"></script>

    <!-- script js -->
    <script src="~/front/js/theme-setting.js"></script>
    <script src="~/front/js/script.js" asp-append-version="true"></script>
    <script src="~/front/js/typeahead.bundle.min.js"></script>
    <script src="~/front/js/typeahead.jquery.min.js"></script>
    <script src="~/front/js/ajax-custom.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MobileMenu.cshtml
<!-- mobile fix menu start -->
<div class="mobile-menu d-sm-none">
    <ul>
        <li>
            <a asp-controller="Home" asp-action="Index" class="active">
                <i data-feather="home"></i>
                <span>Inicio</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0)" class="toggle-category">
                <i data-feather="align-justify"></i>
                <span>Categorías</span>
            </a>
        </li>
        <li>
            <a href="@Url.ActionLink("Index", "Cart")">
                <i data-feather="shopping-bag"></i>
                <span>Ver carrito</span>
            </a>
        </li>
        @if (User.IsAuthenticated())
        {
            <li>
                <a href="wishlist.html">
                    <i data-feather="heart"></i>
                    <span>Deseos</span>
                </a>
            </li>
            <li>
                <a href="user-dashboard.html">
                    <i data-feather="user"></i>
                    <span>Mi cuenta</span>
                </a>
            </li>
        }
        else
        {
            <li>
                <a asp-area="Identity" asp-page="/Account/Login">
                    <i data-feather="user"></i>
                    <span>Iniciar sesión</span>
                </a>
            </li>
        }
    </ul>
</div>
<!-- mobile fix menu end -->

Views/Shared/_Modals.cshtml
<!-- Cart Successful Start -->
<div class="modal fade cart-modal" id="addtocart" tabindex="-1" role="dialog" aria-label="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content ">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="modal-contain">
                    <div>
                        <div class="modal-messages">
                            <i class="fas fa-check"></i> Se ha agregado el producto a tu carrito exitosamente.
                        </div>
                        <div class="modal-product">
                            <div class="modal-contain-img">
                                <img src="~/front/images/fashion/instagram/4.jpg" class="img-fluid blur-up lazyload addtocart__img"
                                     alt="">
                            </div>
                            <div class="modal-contain-details">
                                <h4 class="addtocart__name">Premier Cropped Skinny Jean</h4>
                                <p class="font-light my-2">Cantidad: <span class="addtocart__quantity">1</span></p>
                                <div class="product-total">
                                    <h5>TOTAL : <span class="addtocart__price">$0.00</span></h5>
                                </div>
                                <div class="shop-cart-button mt-3">
                                    <a href="javascript:void(0)"
                                       class="btn default-light-theme conti-button default-theme default-theme-2 rounded" data-bs-dismiss="modal">
                                        CONTINUAR
                                        COMPRANDO
                                    </a>
                                    <a href="@Url.ActionLink("Index", "Cart")"
                                       class="btn default-light-theme conti-button default-theme default-theme-2 rounded">
                                        VER
                                        CARRITO
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="ratio_asos mt-4">
                    <div class="container">
                        <div class="row m-0">
                            <div class="col-sm-12 p-0">
                                <h4 class="mb-lg-4 mb-3 addtocaart__also-bought-title">Clientes también compraron</h4>

                                <div class="product-wrapper product-style-2 p-0 light-arrow bottom-space spacing-slider also-bought-slider">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart Successful End -->
<!-- Quick view modal start -->
<div class="modal fade quick-view-modal" id="quick-view">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-body">
                <div class="row gy-4">
                    <div class="col-lg-6">
                        <div class="quick-view-image">
                            <div class="quick-view-slider ratio_2">
                                <div>
                                    <img src="~/front/images/electronics/product/1.jpg" class="img-fluid bg-img"
                                         alt="product">
                                </div>
                                <div>
                                    <img src="~/front/images/electronics/product/8.jpg" class="img-fluid bg-img"
                                         alt="product">
                                </div>
                                <div>
                                    <img src="~/front/images/electronics/product/9.jpg" class="img-fluid bg-img"
                                         alt="product">
                                </div>
                                <div>
                                    <img src="~/front/images/electronics/product/8.jpg" class="img-fluid bg-img"
                                         alt="product">
                                </div>
                            </div>
                            <div class="quick-nav">
                                <div>
                                    <img src="~/front/images/electronics/product/1.jpg"
                                         class="img-fluid blur-up lazyload" alt="product">
                                </div>
                                <div>
                                    <img src="~/front/images/electronics/product/8.jpg"
                                         class="img-fluid blur-up lazyload" alt="product">
                                </div>
                                <div>
                                    <img src="~/front/images/electronics/product/9.jpg"
                                         class="img-fluid blur-up lazyload" alt="product">
                                </div>
                                <div>
                                    <img src="~/front/images/electronics/product/8.jpg"
                                         class="img-fluid blur-up lazyload" alt="product">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="product-right">
                            <h2 class="mb-2" id="quick-view__title">Producto desconocido</h2>
                            <h6 class="font-light mb-1">Modelo <span id="quick-view__model">LR274</span></h6>
                            <ul class="rating" id="quick-view__rating">
                                <li>
                                    <i class="fas fa-star"></i>
                                </li>
                                <li>
                                    <i class="fas fa-star"></i>
                                </li>
                                <li>
                                    <i class="fas fa-star"></i>
                                </li>
                                <li>
                                    <i class="fas fa-star"></i>
                                </li>
                                <li>
                                    <i class="fas fa-star"></i>
                                </li>
                            </ul>
                            <div class="price mt-3">
                                <h3 id="quick-view__sale-price">$0.00</h3>
                                <h3 id="quick-view__price" class="text-decoration-line-through font-light">$0.00</h3>
                            </div>
                            <div class="product-details">
                                <h4>Descripción</h4>
                                <p id="quick-view__description"></p>
                            </div>
                            <div class="product-btns">
                                <a href="cart.html" class="btn btn-solid-default btn-sm" data-bs-dismiss="modal">
                                    Agregar al carrito
                                </a>
                                <a href="#" id="quick-view__url" class="btn btn-solid-default btn-sm">Ver detalles</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Quick view modal end -->
<!-- Newsletter modal start -->
<div class="modal fade newletter-modal" id="newsletter">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <img src="~/front/images/newletter-icon.png" class="img-fluid blur-up lazyload" alt="">
                <div class="modal-title">
                    <h2 class="tt-title">Sign up for our Newsletter!</h2>
                    <p class="font-light">Never miss any new updates or products we reveal, stay up to date.</p>
                    <p class="font-light">Oh, and it's free!</p>

                    <div class="input-group mb-3">
                        <input placeholder="Email" class="form-control" type="text">

                    </div>

                    <div class="cancel-button text-center">
                        <button class="btn btn-solid-default w-100" data-bs-dismiss="modal"
                                type="button">
                            Submit
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Newsletter modal end -->

Views/Shared/_TapToTopSection.cshtml
<!-- tap to top Section Start -->
<div class="tap-to-top">
    <a href="#home">
        <i class="fas fa-chevron-up"></i>
    </a>
</div>
<!-- tap to top Section End -->

Views/Shared/_ThemeSetting.cshtml
<!-- theme Setting Start -->
<div class="theme-setting">
    <ul>
        <li>
            <button id="darkButton" class="btn btn-sm dark-buttton"><i class="fa fa-moon"></i></button>
        </li>
        <li class="d-none">
            <button class="btn btn-sm rtl-button">RTL</button>
        </li>
        <li class="color-picker d-none">
            <input type="color" class="form-control form-control-color" id="ColorPicker1" value="@(await settings.GetAsync(SettingType.THEME_PRIMARY_COLOR))"
                   title="Choose your color">
        </li>
    </ul>
</div>
<!-- theme Setting End -->

Views/Shared/_URLVariables.cshtml
@Html.Hidden("get-cart-url", Url.ActionLink("Get", "ShoppingCart"))
@Html.Hidden("add-to-cart-url", Url.ActionLink("AddToCart", "ShoppingCart"))
@Html.Hidden("no-image-add-cart-modal-url", Url.Content("~/front/images/fashion/instagram/4.jpg"))
@Html.Hidden("no-image-search-url", Url.Content("~/front/images/electronics/product/1.jpg"))
@Html.Hidden("product-image-url", Url.Content("~/front/images/product/"))
@Html.Hidden("product-detail-url", Url.ActionLink("Detail", "Products", new { productName = "ProductName" }))
@Html.Hidden("cart-page-url", Url.ActionLink("Index", "Cart"))
@Html.Hidden("process-success-payment-url", Url.ActionLink("ProcessSuccessPayment", "Checkout"))
@Html.Hidden("add-to-wishlist-url", Url.ActionLink("Add", "Wishlist"))
@Html.Hidden("remove-to-wishlist-url", Url.ActionLink("Delete", "Wishlist"))